# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c8c917c9b8eba572e79f696c5a40e0117793e67674379c778a5b7aa17f7cb21f5ab6cd29f60d442477883a9bf609ce4924bb83935db257bc684c98e5d9ed7af

test:
  secret_key_base: 84c18e1ae4ea8f5991dcf548a45734516fed0d796989a8a7f40532a77d9e9e5e3c57f5c322e060bdf6fd34a2531636126a603936087364905c8c272915c753a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
